name: github-pipelines

on: workflow_dispatch

jobs:
cache_checkout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      with:
        name: my-checkout-${{ github.run_id }}
        path: ${{ github.workspace }}/**/*

run_lint:
  needs: cache_checkout
  uses: ./.github/workflow/linter.yml
