name: GitHub Actions Demo

run-name: Loan-app CI/CD pipeline

on: [push]

jobs:
  setup:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
      - name: Yarn install
        uses: actions/checkout@v4

      - name: Node Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Yarn build
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: yarn install
      - run: yarn run build
  # linter:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Yarn lint
  #     uses: actions/checkout@v4
  #     - run: yarn lint
