name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Yarn install
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: yarn install
      - run: yarn build
      - run: yarn lint
