name: Check environmental variables

on:
  workflow_dispatch:
    inputs:
      environment:
        print: echo "hello world"

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: 'Vercel Project ID'
        run: echo ${{ vars.VERCEL_PROJECT_ID }}
      - name: 'Vercel Org ID'
        run: echo ${{ vars.VERCEL_ORG_ID }}
      - name: 'Vercel Token'
        run: echo ${{ vars.VERCEL_TOKEN }}
      - name: 'Sample workflow inputs'
        run: ${{ inputs.environment }}
