name: Check environment variables

on:
  workflow_dispatch:

jobs:
  vercel_variables:
    runs-on: ubuntu-latest
    steps:
      - name: 'Vercel Project ID'
        run: echo ${{ vars.VERCEL_PROJECT_ID }}
      - name: 'Vercel Org ID'
        run: echo ${{ vars.VERCEL_ORG_ID }}
      - name: 'Vercel Token'
        run: echo ${{ vars.VERCEL_TOKEN }}
