name: Example github workflow

run-name: ${{ github.event.merge_group.head_commit.message }}

on: [pull_request]

jobs:
  job-name:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Node.js '20'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - run: yarn lint
